Add lnmp module
alibabacloud-automation/terraform-alicloud-lnmp pull request #1
Opened 2020-03-02 10:49 UTC by Rich-yi

2020-03-02 11:18 UTC, zql-tqy commented on examples/complete/README.md
> +<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
这一行去掉吧，没啥用

2020-03-02 11:18 UTC, zql-tqy commented on examples/complete/outputs.tf
> +  description = "The instance id"
补个标点

2020-03-02 12:22 UTC, xiaozhu36 requested changes

2020-03-02 12:22 UTC, xiaozhu36 commented on main.tf
> +  number_of_instances = 1
这个参数暴露出去吧

2020-03-02 12:23 UTC, xiaozhu36 requested changes

2020-03-02 12:23 UTC, xiaozhu36 commented on outputs.tf
> +  value       = concat(module.ecs-instance.this_vswitch_id, [""])[0]
暴露出去后，这个保持list吧

2020-03-10 12:31 UTC, xiaozhu36 requested changes

2020-03-10 12:31 UTC, xiaozhu36 commented on examples/complete/userdata.sh
> +#!/bin/bash
这个地方为啥要再写一遍

2020-03-10 12:31 UTC, xiaozhu36 commented on variables.tf
> +variable "vpc_id" {
这个vpc_id是用来干啥的

2020-03-10 12:31 UTC, xiaozhu36 commented on variables.tf
> +}
为啥有两个password，而且这个default为啥这样写

2020-03-11 06:57 UTC, Rich-yi commented on variables.tf
> +}
脚本中需要传入root，密码应该是第一次登陆mysql使用的是root密码

2020-03-14 02:44 UTC, xiaozhu36 approved these changes

2020-03-14 02:44 UTC, merged